#!/bin/bash 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_1979.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_1980.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_1981.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_1982.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_1983.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_1984.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_1985.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_1986.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_1987.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_1988.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_1989.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_1990.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_1991.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_1992.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_1993.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_1994.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_1995.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_1996.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_1997.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_1998.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_1999.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_2000.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_2001.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_2002.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_2003.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_2004.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_2005.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_2006.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_2007.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_2008.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_2009.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_2010.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_2011.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_2012.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_2013.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_2014.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_2015.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_2016.nc 
